name: Gobelin-vscode

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - develop
  pull_request:

defaults:
  run:
    working-directory: ./gobelin-vscode

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run compile
      - name: Package
        run: npm run bundle
      - name: grab version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: bhowell2/github-substring-action@v1.0.0
        id: vsix-version
        with:
          value: "${{github.ref}}"
          index_of_str: "refs/tags/v"
      - name: Upload assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gobelin-vscode/gobelin-vscode-${{steps.vsix-version.outputs.substring}}.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
